### ISSUE TITLE
Deployment error: Direct installation of an App is disabled

### ISSUE THREAD

**Issue by SimonTheCat** [RocketChat/Rocket.Chat.Apps-engine#283] opened 2020-07-13 21:12 UTC
### Description:

Can't deploy self-created app.

### Steps to reproduce:

```
~/zero# rc-apps deploy --url http://localhost:3000 --username rocket_admin --password password123
packaging your app... packaged!
deploying your app... !
    Error: Deployment error: Direct installation of an App is disabled.

```

### Expected behavior:

Install self-created apps.

### Actual behavior:

Error: Deployment error: Direct installation of an App is disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Debian 10
- Deployment Method: manual installation
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

How to enable installation apps for server?

https://github.com/RocketChat/Rocket.Chat/issues/18154#issue-650812587

**Comment by graywolf336** [comment] 2020-07-13 22:20
Closing because this is working as intended.

https://github.com/RocketChat/Rocket.Chat/blob/292a7c3b30e1946f65680c62a41b6771a6acfabb/app/apps/server/communication/rest.js#L220-L222

**Closed by graywolf336** 2020-07-13 22:20 UTC
