### ISSUE TITLE
Apps should never be offline

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.Apps-engine#245] opened 2020-03-21 14:03 UTC
Whenever an app is Enabled, its bot status should be always online.

**Comment by lolimay** [comment] 2020-03-23 07:49
Hi @marceloschmidt . Is there any situation that app user's status is offline? we only make it offline when it was disabled.

**Comment by marceloschmidt** [comment] 2020-03-23 16:37
I deployed it on covid19.rocket.chat and the app's bot is offline... do you think this is because we changed it's username? we don't want it to be called `app.{appname}`.

**Comment by d-gubert** [comment] 2020-03-24 15:21
Some kind of status change _might_ be controlled via `username` instead of the `_id`... can you please confirm that @lolimay ?

**Comment by lolimay** [comment] 2020-03-24 17:55
Hi @marceloschmidt @d-gubert , I tried to change app user's username but the status is always online. Not sure what's the real reason that causes it.

**Comment by engelgabriel** [comment] 2020-03-29 18:43
The problem happened when we reinstalled the app after the bot had been renamed.

**Comment by lolimay** [comment] 2020-03-29 18:46
> The problem happened when we reinstalled the app after the bot had been renamed.

Hi @engelgabriel ! Thanks for the information provided. Will try to reproduce it and locate the problem

**Comment by d-gubert** [comment] 2020-03-29 18:51
@lolimay I think the app does not check if there is already a user with its `appId` during installation, only during the update. Might be the cause

**Comment by d-gubert** [comment] 2020-03-30 19:26
I'm closing this issue as the solution has been merged https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/252

**Closed by d-gubert** 2020-03-30 19:26 UTC
Labels: :bug: bug
